### ISSUE TITLE
defaulting to null selection is problematic

### ISSUE THREAD

**Issue by sjmiles** [PolymerElements/iron-pages#10]
Suggest `selected: { value: 0 }` so that simple constructions don't appear blank (and therefore broken) to users.

I can make a PR for this issue, but it's annoying to do separately from #9. After #9 is merged, I can send the PR.

**Comment by cdata** [comment]
This sounds like a good idea.

It's possible to make PRs against branches other than `master`. Push your branch-of-a-branch to Github, make a PR, and in the top left drop-down you can select a branch other than `master` to make a PR against:

![image](https://cloud.githubusercontent.com/assets/240083/8111478/f6c5fbd0-1016-11e5-97d5-9fe837ae05a2.png)

**Comment by sjmiles** [comment]
Yes, but what I don't know is what happens if you merge the branch_a without merging the branch_b. They really don't _need_ to depend on each other, they just overlap coincidentally .

**Comment by cdata** [comment]
In that case, the PR for `branch_b` would have to be re-made against `master`. But, nothing would be lost in the process, if that's a concern.

**Comment by notwaldorf** [comment]
I don't think this is an issue anymore; please re-open if i'm wrong!
