### ISSUE TITLE
Google Web Components don't render when used with iron-pages

### ISSUE THREAD

**Issue by beccannlittle** [PolymerElements/iron-pages#13]
I've tested with `google-map`, `google-chart`, and `google-streetview-pano`. When used in conjunction with `iron-pages`, the components don't render. When used with the exact same code but outside of an `iron-pages`, they render fine.

Here's what `google-chart` looks like:
![screen shot 2015-08-26 at 7 35 03 am](https://cloud.githubusercontent.com/assets/6414050/9496585/dee1786a-4bc5-11e5-913b-5c9dc99b4105.png)

Here's what `google-map` looks like:
![screen shot 2015-08-26 at 7 35 32 am](https://cloud.githubusercontent.com/assets/6414050/9496593/eb6f5b4c-4bc5-11e5-837c-7094a7ecc0c2.png)

`google-streetview-pano` acts the same as `google-map`.

Here's the code:

``` html
<iron-pages selected="{{selected}}">

    <div>
        <h3>Google Chart</h3>
        Chart should display here:
        <br><br>
        <google-chart
                type='pie'
                options='{"title": "Distribution of days in 2001Q1"}'
                cols='[{"label":"Month", "type":"string"}, {"label":"Days", "type":"number"}]'
                rows='[["Jan", 31],["Feb", 28],["Mar", 31]]'>
        </google-chart>
        Let's see the same exact code, outside of iron-pages:
        <br>
        <a href="standalones/chart.html">Standalone</a>
    </div>

    <div>
        <h3>Google Map</h3>
        Map should display here:
        <br><br>
        <google-map
                latitude="37.779" 
                longitude="-122.3892">
        </google-map>
        Let's see the same exact code, outside of iron-pages:
        <br>
        <a href="standalones/map.html">Standalone</a>
    </div>

    <div>
        <h3>Google Streetview</h3>
        Panorama should display here:
        <br><br>
        <google-streetview-pano
                pano-id="CWskcsTEZBNXaD8gG-zATA"
                heading="330"
                pitch="-2"
                zoom="0.8"
                disable-default-ui>
        </google-streetview-pano>
        Let's see the same exact code, outside of iron-pages:
        <br>
        <a href="standalones/streetview.html">Standalone</a>
    </div>

</iron-pages>
```

The links to standalone pages contain the exact same code, just without the `iron-pages`. They work as expected.

**Comment by matdehaast** [comment]
Does anyone know how to resolve this issue?

**Comment by cdata** [comment]
Hey guys, depending on whether or not the map is visible at the time that it is rendered, you may need to notify of resize when the page containing the map is made visible. Could you give that a try? The public method to do this on `<google-map>` is `notifyResize`. Alternatively, if the containing host element implements `IronResizableBehavior`, you can call `notifyResize` on it when the page changes.

**Comment by matdehaast** [comment]
Hi cdata

Thanks for the quick reply. Could you elaborate how and where I would need to call that method please, as I am relatively new to polymer. I am working with polymer and dart.

Regards
Matt

**Comment by cdata** [comment]
Sure, here is a contrived example. Please forgive me as I do not know Dart, so I can only show you a JavaScript example:

``` html
<dom-module id="x-example-element">

  <template>

    <iron-pages selected="{{selectedPage}}" attr-for-selected="id">
      <div id="firstPage"> <!-- some content --> </div>
      <div id="secondPage">
        <google-map id="map"></google-map>
      </div>
    </iron-pages>

  </template>

  <script>
    Polymer({

      is: 'x-example-element',

      properties: {
        selectedPage: {
          type: String,
          value: 'firstPage',
          observer: '_selectedPageChanged'
        }
      },

      _selectedPageChanged: function(selectedPage) {
        if (selectedPage === 'secondPage') {
          this.$.map.notifyResize();
        }
      }

    });
  </script>

</dom-module>
```

**Comment by matdehaast** [comment]
Thanks I do understand how to implement that in dart. 

I will give it a try and report back

**Comment by matdehaast** [comment]
Hi Christopher.

Just to give an update. I could not get the notifyResize or any resize function to work. What has worked for me to get the elements to display is to cascade the layout-flex and layout-vertical css tags through all the containers. It seems the google-maps layout was getting a height of 0px assigned and not sure why. Thus I can assign a height but it wasnt dynamic. That is when I tried the cascading of iron-flex-layout and that has done the trick. It seems very long-winded way of doing it though. Thanks for the help. Do you know of a better way to get this to work?

Regards
Matt

**Comment by cdata** [comment]
Hi Mat, thanks for giving it a shot. It's possible, depending on your layout, that the map's container is getting a computed height of `0px`. Would you be able to provide a code sample or JSBin test case that shows how your layout is structured?

**Comment by notwaldorf** [comment]
Closing, since we don't have any repro steps for this. Please re-open with a jsbin if this is still happening (see the CONTRIBUTING.md docs for a sample to get you started)
