### ISSUE TITLE
Gap below iron-pages element?

### ISSUE THREAD

**Issue by WaverleyDesign** [PolymerElements/iron-pages#16]
When an element containing the iron-pages Polymer element is placed on my page, above a paper-toolbar, the image (that has a fixed height) within my iron-pages is not reaching down to the paper-toolbar. Upon inspection in the devtools, I found that the iron.selected class seemed to be always a few pixels taller than the image, though there was nothing in the styles inspector related to height or even width. I will attach a few screenshots because I am finding this issue difficult to explain.

Note that the white space on the side of the image is there intentionally.

![file1](https://cloud.githubusercontent.com/assets/15039951/11046009/7f1db2bc-8776-11e5-937b-aa8c92c8b59e.png)
![file2](https://cloud.githubusercontent.com/assets/15039951/11046011/825085cc-8776-11e5-9e3e-af02d8a6e9c0.png)

**Comment by notwaldorf** [comment]
I can't reproduce this: http://jsbin.com/dejopi/edit?html,output. The `iron-pages` and the div right below it seem to be flush.

Please re-open this issue if it still occurs, with a JSBin containing a set of reproducible steps. Check this element's [CONTRIBUTING.md](../CONTRIBUTING.md) for an example to help you get started.

**Comment by WaverleyDesign** [comment]
Okay, thanks.
