### ISSUE TITLE
iron-pages fails when loaded asynchronously

### ISSUE THREAD

**Issue by MeloJR** [PolymerElements/iron-pages#20]
I am following the steps described in this [article](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/polymer-perf.md) and I found that `iron-pages` is not working at all (but it does show the first page).

I changed the `elements.html` import to be loaded at the beginning of the document instead of dynamically in `loadElements` function inside `app.js` and it then worked. So this seems to indicate that the problem is the asynchronous load.

I also tested `neon-animated-pages` and I found the same problem. If you know a workaround this please let me know.

**Comment by notwaldorf** [comment]
Closing, as this issue doesn't have any code that we can debug. Please provide a JSBin containing a set of reproducible steps, and re-open. Check this element's CONTRIBUTING.md for an example.
