### ISSUE TITLE
How to dynamically add pages to iron-pages

### ISSUE THREAD

**Issue by NamTThai** [PolymerElements/iron-pages#24]
How do I dynamically add pages to iron-pages? Couldn't find documentation anywhere.

Thanks

http://jsbin.com/nuhone/4/edit?html,console,output

**Comment by notwaldorf** [comment]
You need to use `Polymer.dom(ironPage).appendChild(newDiv)`, so that the correct node observers fire off. Here's your JSBin, updated to work: http://jsbin.com/hisoper/edit?html,output

**Comment by masonlouchart** [comment]
Does not work anymore.
