### ISSUE TITLE
Last <section> is sizes differently than the others

### ISSUE THREAD

**Issue by kenchris** [PolymerElements/iron-pages#27]
I have having various sections to switch between in https://weneed-1147.appspot.com/ (click on the FAB, write something, click add and then click on the image).

Without the following patch:

https://github.com/kenchris/weneed/commit/ea5beaa1abe4f9e190e98b935d0cb773c29bd370

the image (the error one) is smaller than on the other pages, using the same code:

![smaller](https://cloud.githubusercontent.com/assets/1101339/12330197/1ef160e0-bae4-11e5-8ee1-ddaa37373f0a.png)

With the above fix, it looks fine:

![fine](https://cloud.githubusercontent.com/assets/1101339/12330222/448d1722-bae4-11e5-92ca-fe0e3bf1bc9c.png)

**Comment by notwaldorf** [comment]
I don't see anything about `iron-pages` in the patch that you linked to, so I don't really understand how it's relevant. Also, your app contains a lot of code and styles, all of which can contribute to a sizing bug; in particular, `iron-pages` doesn't do any styling of its children, so I am skeptical that it's at fault here :(

Without looking at some code, there's not really anything we can do. Please re-open if you can provide a small JSBin reproducing your problem -- you can find an example in the [CONTRIBUTING.md](../CONTRIBUTING.md) file in this repo to get your started.
