### ISSUE TITLE
We should remove 'activateEvent' listener of the 'Polymer.IronSelectableBehavior'

### ISSUE THREAD

**Issue by manifest** [PolymerElements/iron-pages#3]
We should remove 'activateEvent' listener of the 'Polymer.IronSelectableBehavior' for 'iron-pages'.

``` javascript
    ready: function() {
      var p = this.$.pages;
      p._removeListener(p.activateEvent);
    }
```

The problem occurs when the event comes from the element which is content of iron-selector (or iron-pages). It makes impossible to change the current page of 'iron-page' tapping on whatever element located inside the page.

Full example:

``` javascript
<link rel='import' href='../polymer/polymer.html'>
<link rel='import' href='../iron-pages/iron-pages.html'>

<dom-module id='ex-app'>
  <template>

    <iron-pages id='pages' selected='0'>
      <section>
        <h1>Page 0</h1>
        <button on-tap='onInnerTap'>inner button</button>
      </section>
      <section>
        <h1>Page 1</h1>
        <button on-tap='onInnerTap'>inner button</button>
      </section>
      <section>
        <h1>Page 2</h1>
        <button on-tap='onInnerTap'>inner button</button>
      </section>
    </iron-pages>
    <button on-tap='onOuterTap'>outer button</button>

  </template>
</dom-module>

<script>

  Polymer({

    is: 'ex-app',

    ready: function() {
      var p = this.$.pages;
      p._removeListener(p.activateEvent);
    },

    onInnerTap: function() {
      this.$.pages.selected = '1';
      console.log(['inner tap', this.$.pages.selected]);
    },

    onOuterTap: function() {
      this.$.pages.selected = '2';
      console.log(['outer tap', this.$.pages.selected]);
    }

  });
</script>
```

``` javascript
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
    <meta name='viewport' content='width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes'>

    <title>Ex</title>

    <script src="webcomponentsjs/webcomponents-lite.min.js"></script>
    <link rel='import' href='elements/ex-app.html'>
    <style>
      html,body {
        height: 100vh;
        margin: 0;
        background-color: #e5e5e5;
      }
    </style>
  </head>
  <body>

    <ex-app></ex-app>

  </body>
</html>
```

**Comment by cdata** [comment]
Thanks for reporting. I will take a look.

**Comment by hawkett** [comment]
I took some time to put this on [jsbin](http://jsbin.com/gacolo/5/edit) - thanks @manifest for working out an example.

FWIW, I'm not seeing the listener removal helping the problem.

**Comment by manifest** [comment]
@hawkett, since Polymer v1.0 has been released this fix no longer works. To listen to no events we can set 'IronSelectableBehavior.activateEvent' to an empty string according to the in-source documentation.

``` javascript
ready: function() {
  var p = this.$.pages;
  p.activateEvent = '';
}
```

But I still think this behavior should be set by default for the iron-pages element.

**Comment by hawkett** [comment]
Right - we be able to reliably call select() on an iron-pages element.

I've been doing this where I've had the problem:

```
this.$.viewSelector.select(index);
this.$.viewSelector.selectedItem.toggleClass("iron-selected", true);
```

Perhaps a little more resilient to future changes in iron-pages implementation. Perhaps not :) Either solution is not ideal.

**Comment by hawkett** [comment]
After a a bunch of digging have discovered the problem in this issue is _not_ the cause of the problem I [originally posted](https://github.com/PolymerElements/iron-selector/issues/16), they just had very similar effects. Note - I deleted my previous comment in this issue as it contained a workaround for the original problem, but it wasn't applicable to this issue.

I'll add more details on the original problem.
