### ISSUE TITLE
Incompatibility with iOS 9 Safari

### ISSUE THREAD

**Issue by stemuk** [PolymerElements/iron-pages#42]
The Demo of iron-pages is not working on iOS 9 Safari and Safari- based browsers like Chrome for iOS. This may point to a general incompatibility of iron-pages with iOS 9 Safari, is somebody facing the same issues?

-Stefan

**Comment by notwaldorf** [comment]
Hmm the problem is with the demo, not the element -- it seems to be that the `iron-pages` element eats the click, and doesn't bubble it to the document. If we put the click handler on the document, it works fine: http://output.jsbin.com/picexu

I'll update the demo and send a PR!
