### ISSUE TITLE
Animated transitions between pages

### ISSUE THREAD

**Issue by SemonCat** [PolymerElements/iron-pages#5]
very need this.

**Comment by morethanreal** [comment]
Check out https://github.com/PolymerElements/neon-animation for this.

**Comment by scottromack** [comment]
Don't use neon-animation! It's depricated

**Comment by microo8** [comment]
And what can be used instead? How to animate it with pure css?

**Comment by scottromack** [comment]
This is what I am trying to figure out as well. I am using iron-dropdown and you can disable web animations via attributes but it still won't allow simple CSS transitions. It's pretty frustrating.
