### ISSUE TITLE
middleware

### ISSUE THREAD

**Issue by jobizzness** [PolymerElements/iron-pages#60]
### Description

Hi i was thinking to have like a middleware for iron-pages.
        <iron-pages
            selected="[[page]]"
            attr-for-selected="name"
            fallback-selection="404"
            session="[[signedIn]]"
            role="main">
          <biness-home name="home" middleware="auth"></biness-home>
          <biness-404 name="dashboard" middleware="admin"></biness-404>
          <biness-404 name="404" middleware="guest"></biness-404>
        </iron-pages>

### Expected outcome
        <iron-pages
            selected="[[page]]"
            attr-for-selected="name"
            fallback-selection="404"
            session="[[signedIn]]"
            role="main">
          <biness-home name="home" middleware="auth"></biness-home>
          <biness-404 name="dashboard" middleware="admin"></biness-404>
          <biness-404 name="404" middleware="guest"></biness-404>
        </iron-pages>

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by goatandsheep** [comment]
What does `role` do?

**Comment by jobizzness** [comment]
If anyone is interested, i think this can be achieved using switch statements. Here is how i did it. 

`
_middleware(page, old){
            switch(page){
              case 'login':
              case 'signup':
                if(this.user){
                  this.set("route.path", '/');
                }
                break;
              case 'me':
              case 'cart':
              case 'notification':
                if(!this.user){
                  this.set("route.path", '/');
                  this._showLogin();
                }
                break;
            }
          }`

**Comment by jobizzness** [comment]
`_middleware(page, old){
            switch(page){
              case 'login':
              case 'signup':
                if(this.user){
                  this.set("route.path", '/');
                }
                break;
              case 'me':
              case 'cart':
              case 'notification':
                if(!this.user){
                  this.set("route.path", '/');
                  this._showLogin();
                }
                break;
            }
          }`
