### ISSUE TITLE
Any event when selected item changed?

### ISSUE THREAD

**Issue by yiochen** [PolymerElements/iron-pages#7]
In polymer 0.5 I listened to "core-select" event for initializing each page of core-pages since core-pages extends core-selector. Is there an similar event for iron-pages? I tried to set activate-event attribute on iron-pages, but didn't catch any events (maybe I didn't use it correctly).

**Comment by notwaldorf** [comment]
There should be an `iron-select` or `iron-activate` event fired, depending on which one you need.
