### ISSUE TITLE
No change

### ISSUE THREAD

**Issue by glaucomunsberg** [PolymerElements/iron-pages#8]
I can't change the selected page by javascript inside one function, I have a scope problem?

**Comment by AlcaYezz** [comment]
I have this problem too, when I change selected page that work a first time but i can't switch another time. I use console.log before and after selected changes and this value is always reset. I check all my javascript and that doesn't come from her.

**Comment by vl4dt** [comment]
Same condition here, selection only works when executed from Chrome's javascript console:
[YouTube: Video showing the issue](https://youtu.be/z_XqpVQvLeg)

Code involved:

HTML:

``` html
    <iron-pages id="pages" selected="{{selected}}">
    ...
    </iron-pages>
```

JavaScript:

``` javascript
    _onItemClick: function(e) {
      this.selected = 1;

      console.log('selected item: ' + e.detail.item.title);
      console.log('iron-pages::selected = ' + this.$.pages.selected);
    },
```

Before that I tried to just:

``` javascript
    _onItemClick: function(e) {
      this.$.pages.selected = 1;

      console.log('selected item: ' + e.detail.item.title);
      console.log('iron-pages::selected = ' + this.$.pages.selected);
    },
```

with same results.

**Comment by sjmiles** [comment]
These are likely all caused by the same problem described in #3.

**Comment by glaucomunsberg** [comment]
@sjmiles looking through the code I found something curious: when I set the second element using , for example, document.querySelector('iron-papges').selected = 1, the first div lost the class 'iron-selected', but the second div not receives the class.

**Comment by notwaldorf** [comment]
I think this has been fixed. Please re-open if it's still reproducible!
